- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/eerieverse.conf

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
