- hosts: app
  become: yes
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/all_vault.yml

  tasks:
    - name: Install Node.js & Git
      yum:
        name:
          - git
          - nodejs
        state: present

    - name: Pull latest code from Github
      git:
        repo: "https://github.com/YOUR_USERNAME/EerieVerse-DevOps.git"
        dest: /opt/eerieverse
        version: main

    - name: Copy environment variables
      copy:
        dest: /opt/eerieverse/.env
        content: |
          PORT={{ PORT }}
          DBURL={{ DBURL }}
          SECRET_KEY={{ SECRET_KEY }}
          NODE_ENV={{ NODE_ENV }}

    - name: Install Node dependencies
      command: npm install
      args:
        chdir: /opt/eerieverse/server

    - name: Start app (PM2)
      command: pm2 start /opt/eerieverse/server/index.js --name eerieverse
      ignore_errors: yes
