---
- hosts: app
  become: yes
  vars_files:
    - group_vars/all_vault.yml

  tasks:

  - name: Install required packages
    ansible.builtin.yum:
      name:
        - git
        - curl
      state: present

  - name: Install Node.js (LTS)
    ansible.builtin.shell: |
      curl -sL https://rpm.nodesource.com/setup_18.x | bash -
      yum install -y nodejs

  - name: Install PM2
    ansible.builtin.shell: npm install -g pm2

  - name: Clone app repository
    ansible.builtin.git:
      repo: "https://github.com/Rohit72099/Eerieverse2.git"
      dest: /home/ec2-user/app
      version: main

  - name: Create .env file
    ansible.builtin.copy:
      dest: /home/ec2-user/app/.env
      content: |
        PORT={{ PORT }}
        DBURL={{ DBURL }}
        SECRET_KEY={{ SECRET_KEY }}
        NODE_ENV={{ NODE_ENV }}
      owner: ec2-user
      group: ec2-user
      mode: '0600'

  - name: Install dependencies
    ansible.builtin.shell: |
      cd /home/ec2-user/app
      npm install

  - name: Start app with PM2
    ansible.builtin.shell: |
      cd /home/ec2-user/app
      pm2 stop all || true
      pm2 start index.js --name eerieverse
      pm2 save
